#!/usr/bin/env sh

export CONFIG_FILE="${HOME}/.config/chezmoi/chezmoi.yaml"
export CONFIG_DIR="`dirname "${CONFIG_FILE}"`"

if [ ! -d "${CONFIG_DIR}" ]; then
  mkdir -p "${CONFIG_DIR}"
fi

chmod 0700 "${CONFIG_DIR}" .

if [ ! -f ${CONFIG_FILE} ]; then
  cat << EOM > ${CONFIG_FILE}
data:
  user:
    email: me@example.com
    name: My Name
    time_zone: America/Phoenix
  ssh:
    authorized: ''
    public: ''
    private: ''
    config: ''
  admin:
    hosts: []
    - localhost
    apthosts: []
EOM
else
  echo "${CONFIG_FILE} already exists"
fi
